image: node:8.16

before_script:
  - node --version
  - npm --version
  - npm config set unsafe-perm true
  - npm config set loglevel warn --global
  - npm config set registry $NPM_REGISTRY_READ_URL
  - echo "npm registry `npm config get registry`"
  - echo "branch ${CI_BUILD_REF_NAME}"
  - echo "commit ${CI_BUILD_REF}"
  - export SHORT_REF=`echo ${CI_BUILD_REF} | cut -b 1-7`
  - echo "short ${SHORT_REF}"
  - echo "tag ${CI_BUILD_TAG}"
  - echo "build ${CI_BUILD_ID}"

stages:
  - test
  - deploy

test:
  stage: test
  except:
    - tags
  script:
    - npm install
    - npm run build
    - npm run test
    - git checkout -- package-lock.json
    - git status

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm install
    - npm run build
    - npm run test
    - git checkout -- package-lock.json
    - git status
    - echo "publishing to registry $NPM_REGISTRY_PUBLISH_URL"
    - npx lerna publish from-git --registry $NPM_REGISTRY_PUBLISH_URL --yes

# job for deploying examples to Gitlab Pages -- must be named "pages"
# TODO silencing failures for now
#pages:
#  stage: deploy
#  only:
#    - master
#  script:
#    - npm install
#    - npm run build-examples
#  artifacts:
#    paths:
#      - packages/troika-examples
