image: node:8.9

before_script:
  - node --version
  - npm --version
  - npm config set unsafe-perm true
  - npm config set loglevel warn --global
  - npm config set registry https://internal-npm/content/repositories/npm-all/
  - echo "branch ${CI_BUILD_REF_NAME}"
  - echo "commit ${CI_BUILD_REF}"
  - export SHORT_REF=`echo ${CI_BUILD_REF} | cut -b 1-7`
  - echo "short ${SHORT_REF}"
  - echo "tag ${CI_BUILD_TAG}"
  - echo "build ${CI_BUILD_ID}"

stages:
  - test
  - deploy

test:
  stage: test
  except:
    - tags
  script:
    - npm install
    - npm run build
    - npm run test

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm install
    - npm run build
    - npm run test
    - npx lerna publish from-git --yes

